generation_task:
    pattern_identification: 'regex'
    workaround_or_solution: 'solution'
    solution_with_exectuable_code_snippets: 'solution_with_code'

papyrus:
    # model_path: '/usr/src/app/data/checkpoint-25000'
    # base_model_path: '/usr/src/app/data/zephyr-7b-beta'
    model_path: 'data/checkpoint-30000'
    base_model_path: 'data/zephyr-7b-beta'
