llm:
  sleep_time: 3

kb:
  crude_rag_db: True
  search: False
  kg: False
  bice: True
  search_k: 5

template:
  intention_prompt: /home/ec2-user/doojung/regex_my_sandbox_ec2/prompt_templates/topic_module_intention_prompt.yaml
  code_prompt: /home/ec2-user/doojung/regex_my_sandbox_ec2/prompt_templates/topic_module_code_prompt.yaml
  eval_prompt: /home/ec2-user/doojung/regex_my_sandbox_ec2/prompt_templates/topic_module_eval_prompt.yaml
  memory_prompt:   /home/ec2-user/doojung/regex_my_sandbox_ec2/prompt_templates/topic_module_memory_prompt.yaml

vectordb:
  vector_db_path: /home/ec2-user/doojung/external_datasets/catalyst_chromadb 
  vectordb_search_type: mmr
  vectordb_no_of_docs: 3     

bice_encoder:
  return_topk: 5 
  candidate_num: 512
  ciscocom_data_file: data/new_ciscocom_True_True.json
  bi_model_name_or_path: data/all-sentence-t5-large-Final
  ce_model_name_or_path: data/all_ce_model_ms-marco-MiniLM-L-12-v2-Final
  device: cuda
  embed_file_path: data/new_ciscocom_embedding_all-sentence-t5-large-Final_True_True.pt